// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// comp_cpp
NumericVector comp_cpp(NumericVector x);
RcppExport SEXP _CTS_comp_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(comp_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// distMatrix_cpp
NumericMatrix distMatrix_cpp(NumericMatrix V);
RcppExport SEXP _CTS_distMatrix_cpp(SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(distMatrix_cpp(V));
    return rcpp_result_gen;
END_RCPP
}
// combineRows_cpp
NumericMatrix combineRows_cpp(NumericMatrix A, NumericMatrix B);
RcppExport SEXP _CTS_combineRows_cpp(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(combineRows_cpp(A, B));
    return rcpp_result_gen;
END_RCPP
}
// Stat_cpp
double Stat_cpp(NumericMatrix D);
RcppExport SEXP _CTS_Stat_cpp(SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(Stat_cpp(D));
    return rcpp_result_gen;
END_RCPP
}
// Test_cpp
double Test_cpp(NumericMatrix X, NumericMatrix Y, NumericMatrix Z, int R);
RcppExport SEXP _CTS_Test_cpp(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< int >::type R(RSEXP);
    rcpp_result_gen = Rcpp::wrap(Test_cpp(X, Y, Z, R));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CTS_comp_cpp", (DL_FUNC) &_CTS_comp_cpp, 1},
    {"_CTS_distMatrix_cpp", (DL_FUNC) &_CTS_distMatrix_cpp, 1},
    {"_CTS_combineRows_cpp", (DL_FUNC) &_CTS_combineRows_cpp, 2},
    {"_CTS_Stat_cpp", (DL_FUNC) &_CTS_Stat_cpp, 1},
    {"_CTS_Test_cpp", (DL_FUNC) &_CTS_Test_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_CTS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
