# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

comp_cpp <- function(x) {
    .Call(`_CTS_comp_cpp`, x)
}

distMatrix_cpp <- function(V) {
    .Call(`_CTS_distMatrix_cpp`, V)
}

combineRows_cpp <- function(A, B) {
    .Call(`_CTS_combineRows_cpp`, A, B)
}

Stat_cpp <- function(D) {
    .Call(`_CTS_Stat_cpp`, D)
}

Test_cpp <- function(X, Y, Z, R) {
    .Call(`_CTS_Test_cpp`, X, Y, Z, R)
}

